{% set name = "rat" %}
{% set version = "3.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rat-{{ version }}.tar.gz
  sha256: c644cc2f7bbe6be44e40ca7e149c9de7887511faaaeac7b2844e9d133bbb4305

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - rat = rat.cli.rat_cli:main

requirements:
  host:
    - python >=3.6
    - setuptools >=61.0
    - pip
  run:
    - python >=3.6
    - make
    - gfortran
    - ruamel_yaml
    - yaml
    - rasterio
    - xarray
    - geopandas
    - rioxarray
    - earthengine-api
    - pandas
    - numpy
    - netcdf4
    - dask
    - scipy
    - scikit-learn
    - gdown
    - requests
    - shapely
    - matplotlib
    - pyyaml

test:
  imports:
    - rat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/UW-SASWE/RAT
  summary: Resevoir Monitoring using Satellite Remote Sensing
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://rat-satellitedams.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pritamd47
    - SanchitMinocha
