{% set name = "rat" %}
{% set version = "3.0.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rat-{{ version }}.tar.gz
  sha256: d4d2418624686a9d69521fa730d4804b2efc4060c8eb99215d702992b79283b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - rat = rat.cli.rat_cli:main

requirements:
  host:
    - python >=3.6
    - setuptools >=61.0
    - pip
  run:
    - python >=3.6
    - make
    - gfortran
    - wget
    - rasterio
    - xarray
    - geopandas
    - rioxarray
    - earthengine-api
    - pandas
    - numpy
    - netcdf4
    - dask
    - scipy
    - scikit-learn
    - ruamel_yaml
    - yaml
    - gdown
    - plotly
    - cfgrib
    - gdal
    - libnetcdf
    - libgdal-netcdf

test:
  imports:
    - rat
  commands:
    - pip install ruamel_yaml  # installing ruamel-yaml manually using pip as PyPI package name is ruamel.yaml while conda package name is ruamel_yaml, though both can be installed using ruamel_yaml. This is done for pip check.
    - pip install geonetworkx  # installing geonetworkx manually using pip to pass tests. It is not available in conda.
    - pip check
  requires:
    - pip

about:
  home: https://github.com/UW-SASWE/RAT
  summary: Resevoir Monitoring using Satellite Remote Sensing
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://rat-satellitedams.readthedocs.io/en/latest/
  description: |
    The Reservoir Assessment Tool (RAT) uses satellite remote sensing data to monitor 
    water surface area and water level changes in artificial reservoirs. It uses 
    this information, along with topographical information (either derived from satellite 
    data, or in-situ topo maps) to estimate the Storage Change (∆S) in the reservoirs. 
    Additionally, RAT models the Inflow (I) and the Evaporation (E) of each reservoir. 
    Finally, RAT uses the modeled I, and E, and estimated ∆S, to estimate the Outflow (O) 
    from reservoirs. 

extra:
  recipe-maintainers:
    - pritamd47
    - SanchitMinocha
