{% set name = "rat" %}
{% set version = "3.0.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rat-{{ version }}.tar.gz
  sha256: 12a86f2f69a9330a82dfe91ddde2d398f261d1b92719790358cd0180aa4eecce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - rat = rat.cli.rat_cli:main

requirements:
  host:
    - python >=3.6
    - setuptools >=61.0
    - pip
  run:
    - python >=3.6
    - make
    - gfortran
    - wget
    - rasterio
    - xarray
    - geopandas
    - rioxarray
    - earthengine-api
    - pandas
    - numpy
    - netcdf4
    - dask
    - scipy
    - scikit-learn
    - ruamel_yaml
    - yaml
    - gdown
    - plotly
    - cfgrib

test:
  imports:
    - rat
  commands:
    - pip install ruamel_yaml  # installing ruamel-yaml manually using pip as PyPI package name is ruamel.yaml while conda package name is ruamel_yaml, though both can be installed using ruamel_yaml. This is done for pip check.
    - pip install geonetworkx  # installing geonetworkx manually using pip to pass tests. It is not available in conda.
    - pip check
  requires:
    - pip

about:
  home: https://github.com/UW-SASWE/RAT
  summary: Resevoir Monitoring using Satellite Remote Sensing
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://rat-satellitedams.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pritamd47
    - SanchitMinocha
